[package]
name = "mlang_core"
version = "0.1.0"
edition.workspace = true

[dependencies]
mlang_lsp_definition = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
unicase = { workspace = true }