name: Deploy VS Code extension

on: workflow_dispatch
  
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  NODE_VERSION: '18.x'                      # set this to the node version to use (e.g. '8.x', '10.x', '12.x')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm install -g @vscode/vsce

    - name: "Setup cargo"
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: 'Publish'
      run: npm run publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
