name: Deploy VS Code extension

on: workflow_dispatch
  
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  NODE_VERSION: '18.x'                      # set this to the node version to use (e.g. '8.x', '10.x', '12.x')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Build client'
      shell: bash
      run: |
        npm ci
        npm run client:compile --if-present

    - name: "Setup cargo"
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable 
        target: x86_64-pc-windows-gnu

    - name: 'Build server'
      shell: bash
      run: |
        cd ./server
        cargo build --release --bins --target x86_64-pc-windows-gnu
        cp "./target/release/*.exe" -Destination "./"
        cd ..

    - name: 'Publish'
      uses: lannonbr/vsce-action@4.0.0
      with:
        args: "publish -p $VSCE_TOKEN"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
